// //////////////////////////////////////////////////////////////
// RequestContextEcho is the implementation of RequestContext for echo
//
// Created: 2025/12/25 by Chen Ding (Generated by Qwen)
// //////////////////////////////////////////////////////////////

package RequestHandlers

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"io"
	"log"
	"net/http"
	"time"

	"github.com/chendingplano/shared/go/api/ApiTypes"
	"github.com/chendingplano/shared/go/api/ApiUtils"
	"github.com/chendingplano/shared/go/api/databaseutil"
	"github.com/chendingplano/shared/go/api/sysdatastores"
	middleware "github.com/chendingplano/shared/go/auth-middleware"
	"github.com/labstack/echo/v4"
)

type echoContext struct {
	c echo.Context
}

func NewFromEcho(c echo.Context) RequestContext {
	return &echoContext{c: c}
}

func (e *echoContext) Context() context.Context {
	return e.c.Request().Context()
}

func (e *echoContext) GetRequest() *http.Request {
	return e.c.Request()
}

func (e *echoContext) GetBody() io.ReadCloser {
	return e.c.Request().Body
}

func (e *echoContext) FormValue(name string) string {
	return e.c.FormValue(name)
}

func (e *echoContext) GetCookie(name string) string {
	cookie, err := e.c.Cookie(name)
	if err == nil {
		return cookie.Value
	}
	return ""
}

func (e *echoContext) QueryParam(key string) string {
	return e.c.QueryParam(key)
}

func (e *echoContext) GetRedirectURL(
	reqID string,
	token string,
	username string) string {
	redirect_url := ApiTypes.DatabaseInfo.HomeURL
	if redirect_url == "" {
		log.Printf("[req=%s] ***** Alarm missing home_url config (MID_GGL_094), user:%s",
			reqID, username)
		redirect_url = "localhost:5173"
	}
	return redirect_url
}

// func (e *echoContext) SetCookie(cookie *http.Cookie) {
func (e *echoContext) SetCookie(session_id string) {
	is_secure := ApiUtils.IsSecure()
	cookie := new(http.Cookie)
	cookie.Name = "session_id"
	cookie.Value = session_id
	cookie.Path = "/"
	cookie.HttpOnly = true
	cookie.Secure = is_secure
	cookie.SameSite = http.SameSiteStrictMode
	e.c.SetCookie(cookie)
}

func (e *echoContext) ReqID() string {
	if id, ok := e.c.Get(EchoReqIDKey).(string); ok && id != "" {
		return id
	}
	// Generate and store
	id := generateRequestID("e")
	e.c.Set(EchoReqIDKey, id)
	return id
}

func (e *echoContext) SetReqID(reqID string) {
	e.c.Set(EchoReqIDKey, reqID)
}

func (e *echoContext) Bind(reqID string, v interface{}) error {
	return e.c.Bind(v)
}

func (e *echoContext) GetUserInfoByToken(reqID string, token string) (ApiTypes.UserInfo, bool) {
	var user_info ApiTypes.UserInfo
	return user_info, false
}

func (e *echoContext) GetUserInfoByEmail(reqID string, email string) (ApiTypes.UserInfo, bool) {
	user_info, err := sysdatastores.GetUserInfoByEmail(reqID, email)
	if err != nil {
		// Possible reasons:
		// 1. user not found: user not found
		// 2. user pending verify:
		// 3. database error: error: xxx
		// 4. invalid user: (status not active)
		if errors.Is(err, sql.ErrNoRows) {
			// No user found with that email
			log.Printf("[req=%s] No user found for email: %s", reqID, email)
			return user_info, false
		}

		// Real database error
		error_msg := fmt.Sprintf("Database error:%v, email:%s", err, email)
		log.Printf("[req=%s] ***** Alarm:%s", reqID, error_msg)
		return user_info, false
	}

	return user_info, true
}

func (e *echoContext) SaveSession(
	reqID string,
	login_method string,
	session_id string,
	user_name string,
	user_name_type string,
	user_reg_id string,
	user_email string,
	expiry time.Time) error {
	return sysdatastores.SaveSession(login_method, session_id,
		user_name, user_name_type, user_reg_id,
		user_email, expiry)
}

func (e *echoContext) MarkUserVerified(reqID string, email string) error {
	return sysdatastores.MarkUserVerified(reqID, email)
}

func (e *echoContext) UpdateTokenByEmail(reqID string, email string, token string) error {
	return databaseutil.UpdateVTokenByEmail(ApiTypes.DatabaseInfo.DBType,
		ApiTypes.LibConfig.SystemTableNames.TableNameUsers, email, token)
}

func (e *echoContext) UpsertUser(reqID string,
	user_id_type string,
	user_name string,
	hashed_password string,
	user_email string,
	auth_type string,
	status string,
	first_name string,
	last_name string,
	token string,
	avatar string) error {
	// Set the user
	user_info := ApiTypes.UserInfo{}
	user_info.UserName = user_name
	user_info.UserIdType = user_id_type
	user_info.Email = user_email
	user_info.FirstName = first_name
	user_info.LastName = last_name
	user_info.AuthType = auth_type
	user_info.UserStatus = status
	user_info.Password = hashed_password
	user_info.VToken = token

	ok, err := sysdatastores.AddUserNew(reqID, user_info)
	if !ok {
		log_id := sysdatastores.NextActivityLogID()
		error_msg := fmt.Sprintf("Failed creating user (SHD_RCE_123), user_name:%s, email:%s, err:%s, log_id:%d",
			user_info.UserName, user_info.Email, err, log_id)
		log.Printf("[req=%s] ***** Alarm %s (SHD_EML_393)", reqID, error_msg)

		sysdatastores.AddActivityLog(ApiTypes.ActivityLogDef{
			LogID:        log_id,
			ActivityName: ApiTypes.ActivityName_Auth,
			ActivityType: ApiTypes.ActivityType_DatabaseError,
			AppName:      ApiTypes.AppName_Auth,
			ModuleName:   ApiTypes.ModuleName_EmailAuth,
			ActivityMsg:  &error_msg,
			CallerLoc:    "SHD_EML_664"})

		return fmt.Errorf("%s", error_msg)
	}

	return nil
}

func (e *echoContext) IsAuthenticated(reqID string, loc string) (ApiTypes.UserInfo, error) {
	var ctx = e.c
	user_info, err := middleware.IsAuthenticated(ctx, "SHD_RHD_008")
	if err != nil {
		log_id := sysdatastores.NextActivityLogID()
		error_msg := fmt.Sprintf("auth failed, err:%v, log_id:%d", err, log_id)
		sysdatastores.AddActivityLog(ApiTypes.ActivityLogDef{
			LogID:        log_id,
			ActivityName: ApiTypes.ActivityName_JimoRequest,
			ActivityType: ApiTypes.ActivityType_AuthFailure,
			AppName:      ApiTypes.AppName_RequestHandler,
			ModuleName:   ApiTypes.ModuleName_RequestHandler,
			ActivityMsg:  &error_msg,
			CallerLoc:    "SHD_RHD_065"})

		log.Printf("[req:%s] ***** Alarm:%s (SHD_RHD_067)", reqID, error_msg)
		return ApiTypes.UserInfo{}, fmt.Errorf("%s", error_msg)
	}
	return user_info, nil
}

// Private context key (avoids collisions)
var EchoReqIDKey = "echo/reqID"
