// //////////////////////////////////////////////////////////////
// RequestContext is an abstraction of Context. It is used to
// abstract the differences between the underlying framework, such
// as normal Go backend, Pocketbase, etc.
//
// Created: 2025/12/25 by Chen Ding (Generated by Qwen)
package RequestHandlers

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"io"
	"net/http"
	"time"

	"github.com/chendingplano/shared/go/api/ApiTypes"
)

type ReqIDKeyT string

// RequestContext is a framework-agnostic wrapper for request-scoped data
type RequestContext interface {
	// Context returns the underlying Go context (for deadlines, cancellation, values)
	Context() context.Context

	// ReqID returns a unique request ID (guaranteed non-empty)
	ReqID() string

	// SetReqID stores the reqID in the context (idempotent)
	SetReqID(reqID string)

	GetCookie(name string) string
	SetCookie(session_id string)
	IsAuthenticated(reqID string, loc string) (ApiTypes.UserInfo, error)
	FormValue(name string) string
	GetBody() io.ReadCloser
	GetRequest() *http.Request
	Bind(reqID string, v interface{}) error
	QueryParam(key string) string
	GetUserInfoByEmail(reqID string, email string) (ApiTypes.UserInfo, bool)
	GetUserInfoByToken(reqID string, token string) (ApiTypes.UserInfo, bool)
	MarkUserVerified(reqID string, email string) error
	UpdateTokenByEmail(reqID string, email string, token string) error
	VerifyUserPassword(reqID string, email string, plaintextPassword string) (bool, int, string)
	UpdatePassword(reqID string, email string, plaintextPassword string) (bool, int, string)
	GenerateAuthToken(reqID string, email string) (string, error)
	// GetRedirectURL(
	// 	reqID string,
	// 	token string,
	// 	username string) string

	UpsertUser(reqID string,
		user_id_type string,
		user_name string,
		hashed_password string,
		email string,
		auth_type string,
		status string,
		first_name string,
		last_name string,
		token string,
		avatar string) error

	SaveSession(
		reqID string,
		login_method string,
		session_id string,
		user_name string,
		user_name_type string,
		user_reg_id string,
		user_email string,
		expiry time.Time) error
}

// Helper to generate a short, random request ID
func generateRequestID(key string) string {
	bytes := make([]byte, 4) // 4 bytes = 8 hex chars
	if _, err := rand.Read(bytes); err != nil {
		// Fallback if crypto/rand fails (very rare)
		return "fallback-req-id"
	}
	return key + "-" + hex.EncodeToString(bytes)
}
