package loggerutil

///////////////////////////////////////////////////////////////////////////
// MultiHandler implements slog.Handler to write logs to multiple handlers
// simultaneously. MultiHandler is a sub-class from slog.Handler.
// MultiHandler has an array of slog.Handlers and forwards log records to all of them.
// Normally, there should be one stdio handler and one file handler.
// Since MultiHandler implements slog.Handler, it can be used wherever slog.Handler is expected.
// Usage:
//   handlers := []slog.Handler{stdioHandler, fileHandler}
//   multiHandler := loggerutil.MultiHandler{handlers: handlers}
//   logger := slog.New(multiHandler)
//
// Created: 2026-01-30 by Chen Ding (generated by ChatGPT)
///////////////////////////////////////////////////////////////////////////

import (
	"context"
	"log/slog"
)

type MultiHandler struct {
	handlers []slog.Handler
}

func (m MultiHandler) Enabled(ctx context.Context, level slog.Level) bool {
	for _, h := range m.handlers {
		if h.Enabled(ctx, level) {
			return true
		}
	}
	return false
}

func (m MultiHandler) Handle(ctx context.Context, r slog.Record) error {
	for _, h := range m.handlers {
		_ = h.Handle(ctx, r)
	}
	return nil
}

func (m MultiHandler) WithAttrs(attrs []slog.Attr) slog.Handler {
	hs := make([]slog.Handler, 0, len(m.handlers))
	slog.Info("MultiHandler WithAttrs called (SHD_MRT_044)", "num_handlers", len(m.handlers))
	for _, h := range m.handlers {
		hs = append(hs, h.WithAttrs(attrs))
	}
	return MultiHandler{handlers: hs}
}

func (m MultiHandler) WithGroup(name string) slog.Handler {
	hs := make([]slog.Handler, 0, len(m.handlers))
	for _, h := range m.handlers {
		hs = append(hs, h.WithGroup(name))
	}
	return MultiHandler{handlers: hs}
}
