///////////////////////////////////////////////////////
// Description:
// It implements a join_builder that we can use to build
// joins interactively.
// Below are some examples of how to use it to build joins.
// 
// Example 1: Simple join
// const join1 = join_constructor
//     .from('users')
//     .join('profiles')
//     .on('users.id', 'profiles.user_id')
//     .select('name', 'email', 'bio')
//     .embedAs('profile')
//     .build();
//
// This creates:
// {
//   fromTableName: 'users',
//   joinedTableName: 'profiles',
//   onClause: [
//     { sourceFieldName: 'users.id', joinedFieldName: 'profiles.user_id', joinedOpr: '=', dataType: 'string' }
//   ],
//   selectedFields: ['name', 'email', 'bio'],
//   embedName: 'profile'
// }
//
// Example 2: Join with multiple ON conditions and different operators
//const join2 = join_constructor
//    .from('orders')
//    .join('customers')
//    .on('orders.customer_id', 'customers.id')
//    .on('orders.status', 'customers.default_status', '=')
//    .select('customer_name', 'email', 'phone')
//    .embedAs('customer')
//    .build();
//
// Example 3: Join with specific data types
//const join3 = join_constructor
//    .from('products')
//    .join('categories')
//    .on('products.category_id', 'categories.id', '=', 'number')
//    .select('category_name', 'description')
//    .embedAs('category')
//    .build();
//
// Example 4: Multiple joins can be created separately
// const userJoin = join_constructor
//     .from('posts')
//     .join('users')
//     .on('posts.author_id', 'users.id')
//     .select('username', 'avatar')
//     .embedAs('author')
//     .build();
// 
// const commentJoin = join_constructor
//     .from('posts')
//     .join('comments')
//     .on('posts.id', 'comments.post_id')
//     .select('comment_text', 'created_at')
//     .embedAs('latest_comment')
//     .build();
// 
// const joinsArray: JoinDef[] = [userJoin, commentJoin];
//
// Created: 2025/12/14 by Chen Ding (generated by Qwen Coder)
///////////////////////////////////////////////////////

import type { JoinDef, FieldDef } from "$lib/types/CommonTypes";

// Base class for building joins
class JoinBuilder {
    protected joinDef: JoinDef;

    constructor(fromTableName: string, joinedTableName: string, joinType: string) {
        this.joinDef = {
            from_table_name: fromTableName,
            joined_table_name: joinedTableName,
            on_clause: [],
            from_field_defs: [],
            joined_field_defs: [],
            join_type: joinType,
            selected_fields: []
        };
    }

    // Set join type (left_join, right_join, inner_join, join)
    type(joinType: 'left_join' | 'right_join' | 'inner_join' | 'join'): this {
        this.joinDef.join_type = joinType;
        return this;
    }

    // Add ON clause conditions
    on(sourceField: string, joinedField: string, operator: string, dataType: string): this {
        this.joinDef.on_clause.push({
            source_field_name: sourceField,
            joined_field_name: joinedField,
            join_opr: operator,
            data_type: dataType
        });
        return this;
    }

    // Add FromFieldDefs
    fromFieldDefs(field_defs: FieldDef[]): this {
        this.joinDef.from_field_defs.push(...field_defs);
        return this;
    }

    // Add JoinedFieldDefs
    joinedFieldDefs(field_defs: FieldDef[]): this {
        this.joinDef.joined_field_defs.push(...field_defs);
        return this;
    }

    // Add selected fields
    select(...fields: string[]): this {
        this.joinDef.selected_fields.push(...fields);
        return this;
    }

    // Set embed name for field prefixing
    embedAs(embedName: string): this {
        this.joinDef.embed_name = embedName;
        return this;
    }

    // Build the final join definition
    build(): JoinDef {
        return this.joinDef;
    }
}

// Main join constructor class
class JoinConstructor {
    // Start building a join from source table to joined table
    from(sourceTable: string): JoinFromStep {
        return new JoinFromStep(sourceTable);
    }
}

// Intermediate step to specify the joined table
class JoinFromStep {
    private sourceTable: string;

    constructor(sourceTable: string) {
        this.sourceTable = sourceTable;
    }

    // Specify the table to join with
    join(joinedTable: string, joinType: string): JoinBuilder {
        return new JoinBuilder(this.sourceTable, joinedTable, joinType);
    }
}

// Global instance for easy access
const join_builder = new JoinConstructor();

export { 
    join_builder, 
    type JoinDef, 
    JoinConstructor, 
    JoinBuilder, 
    JoinFromStep 
};